/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedSecretsRouteImport } from './routes/_protected/secrets'
import { Route as ProtectedProvidersRouteImport } from './routes/_protected/providers'
import { Route as ProtectedModelsRouteImport } from './routes/_protected/models'
import { Route as ProtectedCodingAgentsRouteImport } from './routes/_protected/coding-agents'
import { Route as ProtectedBenchmarksRouteImport } from './routes/_protected/benchmarks'
import { Route as ProtectedAuditRouteImport } from './routes/_protected/audit'
import { Route as ProtectedProvidersIndexRouteImport } from './routes/_protected/providers/index'
import { Route as ProtectedModelsIndexRouteImport } from './routes/_protected/models/index'
import { Route as ProtectedBenchmarksIndexRouteImport } from './routes/_protected/benchmarks/index'
import { Route as ApiAuthAcceptInviteRouteImport } from './routes/api/auth/accept-invite'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedProvidersProviderIdRouteImport } from './routes/_protected/providers/$providerId'
import { Route as ProtectedModelsAliasesRouteImport } from './routes/_protected/models/aliases'
import { Route as ProtectedBenchmarksOpenrouterRouteImport } from './routes/_protected/benchmarks/openrouter'
import { Route as ProtectedBenchmarksAaRouteImport } from './routes/_protected/benchmarks/aa'
import { Route as ProtectedModelsModelIdSettingsRouteImport } from './routes/_protected/models/$modelId/settings'
import { Route as ProtectedModelsModelIdSettingsTabRouteImport } from './routes/_protected/models/$modelId/settings/$tab'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSecretsRoute = ProtectedSecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedProvidersRoute = ProtectedProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedModelsRoute = ProtectedModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCodingAgentsRoute = ProtectedCodingAgentsRouteImport.update({
  id: '/coding-agents',
  path: '/coding-agents',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedBenchmarksRoute = ProtectedBenchmarksRouteImport.update({
  id: '/benchmarks',
  path: '/benchmarks',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAuditRoute = ProtectedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedProvidersIndexRoute = ProtectedProvidersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedProvidersRoute,
} as any)
const ProtectedModelsIndexRoute = ProtectedModelsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedModelsRoute,
} as any)
const ProtectedBenchmarksIndexRoute =
  ProtectedBenchmarksIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedBenchmarksRoute,
  } as any)
const ApiAuthAcceptInviteRoute = ApiAuthAcceptInviteRouteImport.update({
  id: '/api/auth/accept-invite',
  path: '/api/auth/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedProvidersProviderIdRoute =
  ProtectedProvidersProviderIdRouteImport.update({
    id: '/$providerId',
    path: '/$providerId',
    getParentRoute: () => ProtectedProvidersRoute,
  } as any)
const ProtectedModelsAliasesRoute = ProtectedModelsAliasesRouteImport.update({
  id: '/aliases',
  path: '/aliases',
  getParentRoute: () => ProtectedModelsRoute,
} as any)
const ProtectedBenchmarksOpenrouterRoute =
  ProtectedBenchmarksOpenrouterRouteImport.update({
    id: '/openrouter',
    path: '/openrouter',
    getParentRoute: () => ProtectedBenchmarksRoute,
  } as any)
const ProtectedBenchmarksAaRoute = ProtectedBenchmarksAaRouteImport.update({
  id: '/aa',
  path: '/aa',
  getParentRoute: () => ProtectedBenchmarksRoute,
} as any)
const ProtectedModelsModelIdSettingsRoute =
  ProtectedModelsModelIdSettingsRouteImport.update({
    id: '/$modelId/settings',
    path: '/$modelId/settings',
    getParentRoute: () => ProtectedModelsRoute,
  } as any)
const ProtectedModelsModelIdSettingsTabRoute =
  ProtectedModelsModelIdSettingsTabRouteImport.update({
    id: '/$tab',
    path: '/$tab',
    getParentRoute: () => ProtectedModelsModelIdSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/login': typeof LoginRoute
  '/audit': typeof ProtectedAuditRoute
  '/benchmarks': typeof ProtectedBenchmarksRouteWithChildren
  '/coding-agents': typeof ProtectedCodingAgentsRoute
  '/models': typeof ProtectedModelsRouteWithChildren
  '/providers': typeof ProtectedProvidersRouteWithChildren
  '/secrets': typeof ProtectedSecretsRoute
  '/benchmarks/aa': typeof ProtectedBenchmarksAaRoute
  '/benchmarks/openrouter': typeof ProtectedBenchmarksOpenrouterRoute
  '/models/aliases': typeof ProtectedModelsAliasesRoute
  '/providers/$providerId': typeof ProtectedProvidersProviderIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/accept-invite': typeof ApiAuthAcceptInviteRoute
  '/benchmarks/': typeof ProtectedBenchmarksIndexRoute
  '/models/': typeof ProtectedModelsIndexRoute
  '/providers/': typeof ProtectedProvidersIndexRoute
  '/models/$modelId/settings': typeof ProtectedModelsModelIdSettingsRouteWithChildren
  '/models/$modelId/settings/$tab': typeof ProtectedModelsModelIdSettingsTabRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/audit': typeof ProtectedAuditRoute
  '/coding-agents': typeof ProtectedCodingAgentsRoute
  '/secrets': typeof ProtectedSecretsRoute
  '/': typeof ProtectedIndexRoute
  '/benchmarks/aa': typeof ProtectedBenchmarksAaRoute
  '/benchmarks/openrouter': typeof ProtectedBenchmarksOpenrouterRoute
  '/models/aliases': typeof ProtectedModelsAliasesRoute
  '/providers/$providerId': typeof ProtectedProvidersProviderIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/accept-invite': typeof ApiAuthAcceptInviteRoute
  '/benchmarks': typeof ProtectedBenchmarksIndexRoute
  '/models': typeof ProtectedModelsIndexRoute
  '/providers': typeof ProtectedProvidersIndexRoute
  '/models/$modelId/settings': typeof ProtectedModelsModelIdSettingsRouteWithChildren
  '/models/$modelId/settings/$tab': typeof ProtectedModelsModelIdSettingsTabRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/_protected/audit': typeof ProtectedAuditRoute
  '/_protected/benchmarks': typeof ProtectedBenchmarksRouteWithChildren
  '/_protected/coding-agents': typeof ProtectedCodingAgentsRoute
  '/_protected/models': typeof ProtectedModelsRouteWithChildren
  '/_protected/providers': typeof ProtectedProvidersRouteWithChildren
  '/_protected/secrets': typeof ProtectedSecretsRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/benchmarks/aa': typeof ProtectedBenchmarksAaRoute
  '/_protected/benchmarks/openrouter': typeof ProtectedBenchmarksOpenrouterRoute
  '/_protected/models/aliases': typeof ProtectedModelsAliasesRoute
  '/_protected/providers/$providerId': typeof ProtectedProvidersProviderIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/accept-invite': typeof ApiAuthAcceptInviteRoute
  '/_protected/benchmarks/': typeof ProtectedBenchmarksIndexRoute
  '/_protected/models/': typeof ProtectedModelsIndexRoute
  '/_protected/providers/': typeof ProtectedProvidersIndexRoute
  '/_protected/models/$modelId/settings': typeof ProtectedModelsModelIdSettingsRouteWithChildren
  '/_protected/models/$modelId/settings/$tab': typeof ProtectedModelsModelIdSettingsTabRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/audit'
    | '/benchmarks'
    | '/coding-agents'
    | '/models'
    | '/providers'
    | '/secrets'
    | '/benchmarks/aa'
    | '/benchmarks/openrouter'
    | '/models/aliases'
    | '/providers/$providerId'
    | '/api/auth/$'
    | '/api/auth/accept-invite'
    | '/benchmarks/'
    | '/models/'
    | '/providers/'
    | '/models/$modelId/settings'
    | '/models/$modelId/settings/$tab'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/audit'
    | '/coding-agents'
    | '/secrets'
    | '/'
    | '/benchmarks/aa'
    | '/benchmarks/openrouter'
    | '/models/aliases'
    | '/providers/$providerId'
    | '/api/auth/$'
    | '/api/auth/accept-invite'
    | '/benchmarks'
    | '/models'
    | '/providers'
    | '/models/$modelId/settings'
    | '/models/$modelId/settings/$tab'
  id:
    | '__root__'
    | '/_protected'
    | '/login'
    | '/_protected/audit'
    | '/_protected/benchmarks'
    | '/_protected/coding-agents'
    | '/_protected/models'
    | '/_protected/providers'
    | '/_protected/secrets'
    | '/_protected/'
    | '/_protected/benchmarks/aa'
    | '/_protected/benchmarks/openrouter'
    | '/_protected/models/aliases'
    | '/_protected/providers/$providerId'
    | '/api/auth/$'
    | '/api/auth/accept-invite'
    | '/_protected/benchmarks/'
    | '/_protected/models/'
    | '/_protected/providers/'
    | '/_protected/models/$modelId/settings'
    | '/_protected/models/$modelId/settings/$tab'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAuthAcceptInviteRoute: typeof ApiAuthAcceptInviteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/secrets': {
      id: '/_protected/secrets'
      path: '/secrets'
      fullPath: '/secrets'
      preLoaderRoute: typeof ProtectedSecretsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/providers': {
      id: '/_protected/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProtectedProvidersRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/models': {
      id: '/_protected/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ProtectedModelsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/coding-agents': {
      id: '/_protected/coding-agents'
      path: '/coding-agents'
      fullPath: '/coding-agents'
      preLoaderRoute: typeof ProtectedCodingAgentsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/benchmarks': {
      id: '/_protected/benchmarks'
      path: '/benchmarks'
      fullPath: '/benchmarks'
      preLoaderRoute: typeof ProtectedBenchmarksRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/audit': {
      id: '/_protected/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof ProtectedAuditRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/providers/': {
      id: '/_protected/providers/'
      path: '/'
      fullPath: '/providers/'
      preLoaderRoute: typeof ProtectedProvidersIndexRouteImport
      parentRoute: typeof ProtectedProvidersRoute
    }
    '/_protected/models/': {
      id: '/_protected/models/'
      path: '/'
      fullPath: '/models/'
      preLoaderRoute: typeof ProtectedModelsIndexRouteImport
      parentRoute: typeof ProtectedModelsRoute
    }
    '/_protected/benchmarks/': {
      id: '/_protected/benchmarks/'
      path: '/'
      fullPath: '/benchmarks/'
      preLoaderRoute: typeof ProtectedBenchmarksIndexRouteImport
      parentRoute: typeof ProtectedBenchmarksRoute
    }
    '/api/auth/accept-invite': {
      id: '/api/auth/accept-invite'
      path: '/api/auth/accept-invite'
      fullPath: '/api/auth/accept-invite'
      preLoaderRoute: typeof ApiAuthAcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/providers/$providerId': {
      id: '/_protected/providers/$providerId'
      path: '/$providerId'
      fullPath: '/providers/$providerId'
      preLoaderRoute: typeof ProtectedProvidersProviderIdRouteImport
      parentRoute: typeof ProtectedProvidersRoute
    }
    '/_protected/models/aliases': {
      id: '/_protected/models/aliases'
      path: '/aliases'
      fullPath: '/models/aliases'
      preLoaderRoute: typeof ProtectedModelsAliasesRouteImport
      parentRoute: typeof ProtectedModelsRoute
    }
    '/_protected/benchmarks/openrouter': {
      id: '/_protected/benchmarks/openrouter'
      path: '/openrouter'
      fullPath: '/benchmarks/openrouter'
      preLoaderRoute: typeof ProtectedBenchmarksOpenrouterRouteImport
      parentRoute: typeof ProtectedBenchmarksRoute
    }
    '/_protected/benchmarks/aa': {
      id: '/_protected/benchmarks/aa'
      path: '/aa'
      fullPath: '/benchmarks/aa'
      preLoaderRoute: typeof ProtectedBenchmarksAaRouteImport
      parentRoute: typeof ProtectedBenchmarksRoute
    }
    '/_protected/models/$modelId/settings': {
      id: '/_protected/models/$modelId/settings'
      path: '/$modelId/settings'
      fullPath: '/models/$modelId/settings'
      preLoaderRoute: typeof ProtectedModelsModelIdSettingsRouteImport
      parentRoute: typeof ProtectedModelsRoute
    }
    '/_protected/models/$modelId/settings/$tab': {
      id: '/_protected/models/$modelId/settings/$tab'
      path: '/$tab'
      fullPath: '/models/$modelId/settings/$tab'
      preLoaderRoute: typeof ProtectedModelsModelIdSettingsTabRouteImport
      parentRoute: typeof ProtectedModelsModelIdSettingsRoute
    }
  }
}

interface ProtectedBenchmarksRouteChildren {
  ProtectedBenchmarksAaRoute: typeof ProtectedBenchmarksAaRoute
  ProtectedBenchmarksOpenrouterRoute: typeof ProtectedBenchmarksOpenrouterRoute
  ProtectedBenchmarksIndexRoute: typeof ProtectedBenchmarksIndexRoute
}

const ProtectedBenchmarksRouteChildren: ProtectedBenchmarksRouteChildren = {
  ProtectedBenchmarksAaRoute: ProtectedBenchmarksAaRoute,
  ProtectedBenchmarksOpenrouterRoute: ProtectedBenchmarksOpenrouterRoute,
  ProtectedBenchmarksIndexRoute: ProtectedBenchmarksIndexRoute,
}

const ProtectedBenchmarksRouteWithChildren =
  ProtectedBenchmarksRoute._addFileChildren(ProtectedBenchmarksRouteChildren)

interface ProtectedModelsModelIdSettingsRouteChildren {
  ProtectedModelsModelIdSettingsTabRoute: typeof ProtectedModelsModelIdSettingsTabRoute
}

const ProtectedModelsModelIdSettingsRouteChildren: ProtectedModelsModelIdSettingsRouteChildren =
  {
    ProtectedModelsModelIdSettingsTabRoute:
      ProtectedModelsModelIdSettingsTabRoute,
  }

const ProtectedModelsModelIdSettingsRouteWithChildren =
  ProtectedModelsModelIdSettingsRoute._addFileChildren(
    ProtectedModelsModelIdSettingsRouteChildren,
  )

interface ProtectedModelsRouteChildren {
  ProtectedModelsAliasesRoute: typeof ProtectedModelsAliasesRoute
  ProtectedModelsIndexRoute: typeof ProtectedModelsIndexRoute
  ProtectedModelsModelIdSettingsRoute: typeof ProtectedModelsModelIdSettingsRouteWithChildren
}

const ProtectedModelsRouteChildren: ProtectedModelsRouteChildren = {
  ProtectedModelsAliasesRoute: ProtectedModelsAliasesRoute,
  ProtectedModelsIndexRoute: ProtectedModelsIndexRoute,
  ProtectedModelsModelIdSettingsRoute:
    ProtectedModelsModelIdSettingsRouteWithChildren,
}

const ProtectedModelsRouteWithChildren = ProtectedModelsRoute._addFileChildren(
  ProtectedModelsRouteChildren,
)

interface ProtectedProvidersRouteChildren {
  ProtectedProvidersProviderIdRoute: typeof ProtectedProvidersProviderIdRoute
  ProtectedProvidersIndexRoute: typeof ProtectedProvidersIndexRoute
}

const ProtectedProvidersRouteChildren: ProtectedProvidersRouteChildren = {
  ProtectedProvidersProviderIdRoute: ProtectedProvidersProviderIdRoute,
  ProtectedProvidersIndexRoute: ProtectedProvidersIndexRoute,
}

const ProtectedProvidersRouteWithChildren =
  ProtectedProvidersRoute._addFileChildren(ProtectedProvidersRouteChildren)

interface ProtectedRouteChildren {
  ProtectedAuditRoute: typeof ProtectedAuditRoute
  ProtectedBenchmarksRoute: typeof ProtectedBenchmarksRouteWithChildren
  ProtectedCodingAgentsRoute: typeof ProtectedCodingAgentsRoute
  ProtectedModelsRoute: typeof ProtectedModelsRouteWithChildren
  ProtectedProvidersRoute: typeof ProtectedProvidersRouteWithChildren
  ProtectedSecretsRoute: typeof ProtectedSecretsRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAuditRoute: ProtectedAuditRoute,
  ProtectedBenchmarksRoute: ProtectedBenchmarksRouteWithChildren,
  ProtectedCodingAgentsRoute: ProtectedCodingAgentsRoute,
  ProtectedModelsRoute: ProtectedModelsRouteWithChildren,
  ProtectedProvidersRoute: ProtectedProvidersRouteWithChildren,
  ProtectedSecretsRoute: ProtectedSecretsRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthAcceptInviteRoute: ApiAuthAcceptInviteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
