/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedProvidersRouteImport } from './routes/_protected/providers'
import { Route as ProtectedModelsRouteImport } from './routes/_protected/models'
import { Route as ProtectedModelsIndexRouteImport } from './routes/_protected/models/index'
import { Route as ApiAuthAcceptInviteRouteImport } from './routes/api/auth/accept-invite'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedModelsAliasesRouteImport } from './routes/_protected/models/aliases'
import { Route as ProtectedModelsModelIdSettingsRouteImport } from './routes/_protected/models/$modelId/settings'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedProvidersRoute = ProtectedProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedModelsRoute = ProtectedModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedModelsIndexRoute = ProtectedModelsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedModelsRoute,
} as any)
const ApiAuthAcceptInviteRoute = ApiAuthAcceptInviteRouteImport.update({
  id: '/api/auth/accept-invite',
  path: '/api/auth/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedModelsAliasesRoute = ProtectedModelsAliasesRouteImport.update({
  id: '/aliases',
  path: '/aliases',
  getParentRoute: () => ProtectedModelsRoute,
} as any)
const ProtectedModelsModelIdSettingsRoute =
  ProtectedModelsModelIdSettingsRouteImport.update({
    id: '/$modelId/settings',
    path: '/$modelId/settings',
    getParentRoute: () => ProtectedModelsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/login': typeof LoginRoute
  '/models': typeof ProtectedModelsRouteWithChildren
  '/providers': typeof ProtectedProvidersRoute
  '/models/aliases': typeof ProtectedModelsAliasesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/accept-invite': typeof ApiAuthAcceptInviteRoute
  '/models/': typeof ProtectedModelsIndexRoute
  '/models/$modelId/settings': typeof ProtectedModelsModelIdSettingsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/providers': typeof ProtectedProvidersRoute
  '/': typeof ProtectedIndexRoute
  '/models/aliases': typeof ProtectedModelsAliasesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/accept-invite': typeof ApiAuthAcceptInviteRoute
  '/models': typeof ProtectedModelsIndexRoute
  '/models/$modelId/settings': typeof ProtectedModelsModelIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/_protected/models': typeof ProtectedModelsRouteWithChildren
  '/_protected/providers': typeof ProtectedProvidersRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/models/aliases': typeof ProtectedModelsAliasesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/accept-invite': typeof ApiAuthAcceptInviteRoute
  '/_protected/models/': typeof ProtectedModelsIndexRoute
  '/_protected/models/$modelId/settings': typeof ProtectedModelsModelIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/models'
    | '/providers'
    | '/models/aliases'
    | '/api/auth/$'
    | '/api/auth/accept-invite'
    | '/models/'
    | '/models/$modelId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/providers'
    | '/'
    | '/models/aliases'
    | '/api/auth/$'
    | '/api/auth/accept-invite'
    | '/models'
    | '/models/$modelId/settings'
  id:
    | '__root__'
    | '/_protected'
    | '/login'
    | '/_protected/models'
    | '/_protected/providers'
    | '/_protected/'
    | '/_protected/models/aliases'
    | '/api/auth/$'
    | '/api/auth/accept-invite'
    | '/_protected/models/'
    | '/_protected/models/$modelId/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAuthAcceptInviteRoute: typeof ApiAuthAcceptInviteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/providers': {
      id: '/_protected/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProtectedProvidersRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/models': {
      id: '/_protected/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ProtectedModelsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/models/': {
      id: '/_protected/models/'
      path: '/'
      fullPath: '/models/'
      preLoaderRoute: typeof ProtectedModelsIndexRouteImport
      parentRoute: typeof ProtectedModelsRoute
    }
    '/api/auth/accept-invite': {
      id: '/api/auth/accept-invite'
      path: '/api/auth/accept-invite'
      fullPath: '/api/auth/accept-invite'
      preLoaderRoute: typeof ApiAuthAcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/models/aliases': {
      id: '/_protected/models/aliases'
      path: '/aliases'
      fullPath: '/models/aliases'
      preLoaderRoute: typeof ProtectedModelsAliasesRouteImport
      parentRoute: typeof ProtectedModelsRoute
    }
    '/_protected/models/$modelId/settings': {
      id: '/_protected/models/$modelId/settings'
      path: '/$modelId/settings'
      fullPath: '/models/$modelId/settings'
      preLoaderRoute: typeof ProtectedModelsModelIdSettingsRouteImport
      parentRoute: typeof ProtectedModelsRoute
    }
  }
}

interface ProtectedModelsRouteChildren {
  ProtectedModelsAliasesRoute: typeof ProtectedModelsAliasesRoute
  ProtectedModelsIndexRoute: typeof ProtectedModelsIndexRoute
  ProtectedModelsModelIdSettingsRoute: typeof ProtectedModelsModelIdSettingsRoute
}

const ProtectedModelsRouteChildren: ProtectedModelsRouteChildren = {
  ProtectedModelsAliasesRoute: ProtectedModelsAliasesRoute,
  ProtectedModelsIndexRoute: ProtectedModelsIndexRoute,
  ProtectedModelsModelIdSettingsRoute: ProtectedModelsModelIdSettingsRoute,
}

const ProtectedModelsRouteWithChildren = ProtectedModelsRoute._addFileChildren(
  ProtectedModelsRouteChildren,
)

interface ProtectedRouteChildren {
  ProtectedModelsRoute: typeof ProtectedModelsRouteWithChildren
  ProtectedProvidersRoute: typeof ProtectedProvidersRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedModelsRoute: ProtectedModelsRouteWithChildren,
  ProtectedProvidersRoute: ProtectedProvidersRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthAcceptInviteRoute: ApiAuthAcceptInviteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
