import {
  LITELLM_ALIAS_GLOBAL_FALLBACK_OVERRIDE_DEFAULT,
  LITELLM_ALIAS_INCLUDE_AGENTS_DEFAULT,
  LITELLM_ALIAS_INCLUDE_CATEGORIES_DEFAULT,
  LITELLM_ALIAS_PREFIX_DEFAULT,
  LITELLM_ALIAS_SCHEMA_URL_DEFAULT,
  type LitellmAliasPluginConfig,
} from "@lite-llm/agents-repository/schemas";

export const litellmAliasPluginDefaults: LitellmAliasPluginConfig = {
  $schema: LITELLM_ALIAS_SCHEMA_URL_DEFAULT,
  aliasPrefix: LITELLM_ALIAS_PREFIX_DEFAULT,
  includeAgents: LITELLM_ALIAS_INCLUDE_AGENTS_DEFAULT,
  includeCategories: LITELLM_ALIAS_INCLUDE_CATEGORIES_DEFAULT,
  globalFallbackOverride: LITELLM_ALIAS_GLOBAL_FALLBACK_OVERRIDE_DEFAULT,
};
