CREATE TABLE "model_proxy_benchmarks" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"aa_model_id" text NOT NULL,
	"name" text NOT NULL,
	"slug" text,
	"creator_id" text,
	"creator_name" text NOT NULL,
	"creator_slug" text,
	"intelligence_index" double precision,
	"coding_index" double precision,
	"math_index" double precision,
	"mmlu_pro" double precision,
	"gpqa" double precision,
	"hle" double precision,
	"livecodebench" double precision,
	"scicode" double precision,
	"math_500" double precision,
	"aime" double precision,
	"aime_25" double precision,
	"tau2" double precision,
	"ifbench" double precision,
	"lcr" double precision,
	"terminalbench_hard" double precision,
	"price_input_1m_tokens" double precision,
	"price_output_1m_tokens" double precision,
	"price_blended_1m_tokens" double precision,
	"median_output_tokens_per_second" double precision,
	"median_ttft_seconds" double precision,
	"median_ttft_answer_seconds" double precision,
	"source_url" text NOT NULL,
	"fetched_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "model_proxy_benchmarks_aa_model_id_unique" UNIQUE("aa_model_id")
);
