import type { AnalyticsCapabilities } from '@lite-llm/analytics-types';

export const DATABASE_CAPABILITIES: AnalyticsCapabilities = {
  spendByModel: true,
  spendByUser: true,
  spendByKey: true,
  spendLogs: true,
  metricsSummary: true,
  dailySpendTrend: true,
  tokenDistribution: true,
  performanceMetrics: true,
  hourlyUsagePatterns: true,
  apiKeyStats: true,
  costEfficiency: true,
  modelDistribution: true,
  dailyTokenTrend: true,
  modelStatistics: true,
  models: true,
  errorLogs: true,
  detailedLatency: true,
  logMerge: true,
  filterOptions: true,
  createModel: true,
  updateModel: true,
  deleteModel: true,
  mergeModels: true,
  deleteModelLogs: true,
  agentRouting: true,
  agentConfigFile: true,
};

export const LIMITED_CAPABILITIES: AnalyticsCapabilities = {
  spendByModel: true,
  spendByUser: true,
  spendByKey: true,
  spendLogs: true,
  metricsSummary: true,
  dailySpendTrend: true,
  tokenDistribution: true,
  performanceMetrics: true,
  hourlyUsagePatterns: true,
  apiKeyStats: true,
  costEfficiency: true,
  modelDistribution: true,
  dailyTokenTrend: true,
  modelStatistics: true,
  models: true,
  errorLogs: true,
  detailedLatency: true,
  logMerge: true,
  filterOptions: true,
  createModel: false,
  updateModel: true,
  deleteModel: false,
  mergeModels: false,
  deleteModelLogs: false,
  agentRouting: false,
  agentConfigFile: false,
};

export const API_CAPABILITIES: AnalyticsCapabilities = {
  spendByModel: true,
  spendByUser: true,
  spendByKey: true,
  spendLogs: true,
  metricsSummary: true,
  dailySpendTrend: true,
  tokenDistribution: true,
  performanceMetrics: true,
  hourlyUsagePatterns: true,
  apiKeyStats: true,
  costEfficiency: true,
  modelDistribution: true,
  dailyTokenTrend: true,
  modelStatistics: true,
  models: true,
  errorLogs: false,
  detailedLatency: false,
  logMerge: false,
  filterOptions: false,
  createModel: false,
  updateModel: false,
  deleteModel: false,
  mergeModels: false,
  deleteModelLogs: false,
  agentRouting: false,
  agentConfigFile: false,
};
