export const queryKeys = {
  models: ["models"],
  modelStatistics: (days) => ["model-statistics", days],
  errorLogs: (limit) => ["error-logs", limit],
  dashboardMetrics: (days) => ["dashboard", "metrics", days],
  dashboardSpendByModel: (days) => ["dashboard", "spend-by-model", days],
  dashboardSpendByUser: (days) => ["dashboard", "spend-by-user", days],
  dashboardDailySpendTrend: (days) => ["dashboard", "daily-spend-trend", days],
  dashboardTokenDistribution: (days) => [
    "dashboard",
    "token-distribution",
    days,
  ],
  dashboardPerformance: (days) => ["dashboard", "performance", days],
  dashboardHourlyPatterns: (days) => ["dashboard", "hourly-patterns", days],
  dashboardApiKeyStats: (days) => ["dashboard", "api-key-stats", days],
  dashboardCostEfficiency: (days) => ["dashboard", "cost-efficiency", days],
  dashboardModelDistribution: (days) => [
    "dashboard",
    "model-distribution",
    days,
  ],
  dashboardDailyTokenTrend: (days) => ["dashboard", "daily-token-trend", days],
  spendLogs: (params) => [
    "spend-logs",
    params.page,
    params.pageSize,
    params.model ?? "",
    params.user ?? "",
    params.startDate ?? "",
    params.endDate ?? "",
  ],
  agentRoutingData: ["agent-routing-data"],
  agentRoutingAliases: ["agent-routing-aliases"],
  agentDefinitions: ["agent-definitions"],
  modelDetailDailySpend: (model, days) => [
    "model-detail",
    "daily-spend",
    model,
    days,
  ],
  modelDetailDailyTokens: (model, days) => [
    "model-detail",
    "daily-tokens",
    model,
    days,
  ],
  modelDetailHourlyUsage: (model, days) => [
    "model-detail",
    "hourly-usage",
    model,
    days,
  ],
  modelDetailLatencyTrend: (model, days) => [
    "model-detail",
    "latency-trend",
    model,
    days,
  ],
  modelDetailErrorBreakdown: (model, days) => [
    "model-detail",
    "error-breakdown",
    model,
    days,
  ],
  modelDetailDailyErrors: (model, days) => [
    "model-detail",
    "daily-errors",
    model,
    days,
  ],
  modelDetailTopUsers: (model, days) => [
    "model-detail",
    "top-users",
    model,
    days,
  ],
  modelDetailTopApiKeys: (model, days) => [
    "model-detail",
    "top-api-keys",
    model,
    days,
  ],
  modelDetailCacheHitRate: (model, days) => [
    "model-detail",
    "cache-hit-rate",
    model,
    days,
  ],
  modelDetailTTFT: (model, days) => ["model-detail", "ttft", model, days],
  modelDetailStatusDistribution: (model, days) => [
    "model-detail",
    "status-distribution",
    model,
    days,
  ],
  modelDetailProviderBreakdown: (model, days) => [
    "model-detail",
    "provider-breakdown",
    model,
    days,
  ],
  healthCheckResults: (params) => [
    "health-check",
    "results",
    params.limit,
    params.offset,
    params.model ?? "",
    params.since ?? "",
  ],
  healthCheckLatest: ["health-check", "latest"],
  healthCheckSummary: ["health-check", "summary"],
};
